language: node_js
node_js:
  - "5"
  - "4"

services:
  - rabbitmq
  - mongodb

before_script:
  - npm install -g abao
  - npm start &
  - sleep 2

script:
  - npm test
  - npm run-script test-api

sudo: required